#!/usr/bin/groovy
@Library('github.com/sunhao-bj/fabric8-pipeline-library@v2.2.4')
def utils = new io.fabric8.Utils()

def versionPrefix = ""
try {
  versionPrefix = VERSION_PREFIX
} catch (Throwable e) {
  versionPrefix = "1.0"
}

def canaryVersion = "${versionPrefix}.${env.BUILD_NUMBER}"

clientsNode{
  env.setProperty('FABRIC8_DOCKER_REGISTRY_SERVICE_HOST', registryHost)
  env.setProperty('FABRIC8_DOCKER_REGISTRY_SERVICE_PORT', registryPort)

  def envStage = DEPLOY_NAMESPACE

  checkout scm
//  git GIT_URL

  stage 'Canary release'
  echo 'NOTE: running pipelines for the first time will take longer as build and base docker images are pulled onto the node'
  if (!fileExists ('Dockerfile')) {
    writeFile file: 'Dockerfile', text: 'FROM registry.timeondata.com/fabric8/swift:2.2-SNAPSHOT-onbuild'
  }

  performCanaryRelease {
    version = canaryVersion
  }
  
  def rc = getKubernetesJson {
    port = 8080
    label = 'swift'
    icon = 'https://cdn.rawgit.com/fabric8io/fabric8-console/master/img/icons/swift.png'
    version = canaryVersion
    imageName = clusterImageName
    exposeApp = IS_EXPOSE
  }

  stage 'Rollout Staging'
  kubernetesApply(file: rc, environment: envStage)
}
