#!/usr/bin/groovy
@Library('github.com/MrChencc/dos-pipeline-test@master')
def dummy

import com.tod.CostomPipelineUtil

mavenNode {
    ws {
        env.setProperty('FABRIC8_DOCKER_REGISTRY_SERVICE_HOST', registryHost)
        env.setProperty('FABRIC8_DOCKER_REGISTRY_SERVICE_PORT', registryPort)
        checkout scm

        def costomConfigStr = readFile "CostomMavenConfig.json" // 读取配置文件
        def costomConfig = CostomPipelineUtil.getJsonPipelineConfig(costomConfigStr)
        
        container(name: 'maven') {
            stage('Maven build') {
                sh 'source /etc/profile'
                sh costomConfig.build.buildShell
            }
            // stage('Package and Namespace') {
            //     def replace = dosReplaceYaml {}
            //     sh replace
            // }
            stage('docker build') {
                def buildShell = 
                mavenCanaryRelease {
                    version = 'latest'
                    pom = costomConfig.build.pomfile
                    dockerfilePath = costomConfig.build.dockerfile
                }
            }

        // TODO 继续处理

            stage 'get yaml and env'
            def yaml = getKubernetesYaml{
                port = '29164'
                label = 'dos-proj'
                icon = 'https://cdn.rawgit.com/fabric8io/fabric8/dc05040/website/src/images/logos/spring-boot.svg'
                version = 'latest'
                pom = 'PROJECT-GENERATOR/pom.xml'
            }
            def envTest = 'dosproj-pipeline-test'

            stage('deploy application') {
                kubernetesApply(file: yaml, environment: envTest)
            }
        }
    }
}