#!/usr/bin/groovy
@Library('github.com/MrChencc/dos-pipeline-test@master')
def dummy
mavenNode {
    ws {
        env.setProperty('FABRIC8_DOCKER_REGISTRY_SERVICE_HOST', registryHost)
        env.setProperty('FABRIC8_DOCKER_REGISTRY_SERVICE_PORT', registryPort)
        def costomConfigStr = costomMavenConfig // 文字形式的配置信息
        checkout scm
        // TODO 继续处理
        container(name: 'maven') {
            stage('Maven build') {
                sh 'source /etc/profile'
                sh 'mvn -f pom-project-generator.xml clean package -DskipTests'
            }
            stage('Package and Namespace') {
                def replace = dosReplaceYaml {}
                sh replace
            }
            stage('docker push') {
                mavenCanaryRelease {
                    version = 'latest'
                    pom = 'PROJECT-GENERATOR/pom.xml'
                    dockerfilePath = 'PROJECT-GENERATOR/Dockerfile'
                }
            }

            stage 'get yaml and env'
            def yaml = getKubernetesYaml{
                port = '29164'
                label = 'dos-proj'
                icon = 'https://cdn.rawgit.com/fabric8io/fabric8/dc05040/website/src/images/logos/spring-boot.svg'
                version = 'latest'
                pom = 'PROJECT-GENERATOR/pom.xml'
            }
            def envTest = 'dosproj-pipeline-test'

            stage('deploy application') {
                kubernetesApply(file: yaml, environment: envTest)
            }
        }
    }
}